name: WolvSK
main: fr.nashoba24.wolvsk.WolvSK
authors: [Nashoba24, forked by Grcq]
version: 1.7.2
depend: [Skript]
softdepend: [ASkyBlock, EssentialsX, GuardianBeamAPI, PlayerPoints, ProtocolLib, SuperTrails]
api-version: "1.13"